version: "3.9"

services:
  api:
    build: ./app
    environment:
      - LLM_ENDPOINT=http://llm:8001/v1/chat/completions
      - LLM_MODEL=mixtral-8x7b-instruct
      - CORS_ORIGINS=http://localhost:4173
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
      - neo4j

  llm:
    image: ghcr.io/huggingface/text-generation-inference:1.3
    environment:
      - MODEL_ID=mistralai/Mixtral-8x7B-Instruct-v0.1
    ports:
      - "8001:80"

  qdrant:
    image: qdrant/qdrant:v1.8.2
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage

  neo4j:
    image: neo4j:5.21
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j_data:/data